### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kryostase** [Forien/foundryvtt-forien-unidentified-items#8] opened 2020-06-27 11:42 UTC
**Module Version:** v0.1.4

**Describe the bug**
In PF2e you can't mystify an item from an actor sheet. Works only in the sidebar itself.

Thats the Error msg when you hit mystify on an actors item:
_Identification.js:13 Uncaught (in promise) TypeError: Cannot read property 'type' of null
    at Function.mystify (Identification.js:13)
    at Object.onclick (init.mjs:72)
    at HTMLAnchorElement.<anonymous> (foundry.js:3960)
    at HTMLAnchorElement.dispatch (jquery.min.js:2)
    at HTMLAnchorElement.v.handle (jquery.min.js:2)_

**Browser:**
chrome

**Foundry Version:** 
0.64

**Game System:** 
PF2e

**Comment by Forien** [comment] 2020-06-27 11:44
Duplicate of #3

**Closed** 2020-06-27 11:44 UTC
Labels: duplicate
