### ISSUE TITLE
[BUG] In PF2, unidentified items are classified as weapons

### ISSUE THREAD

**Issue by apoapostolov** [Forien/foundryvtt-forien-unidentified-items#10] opened 2020-06-28 17:18 UTC
In PF2 systems, the unidentified item template is considered weapon when added to inventory rather than treasure. This makes it appear among the weapons and create a strike without proficiency, etc.

**Comment by Forien** [comment] 2020-06-28 17:23
Possible Duplicate of #5 

Basically, only retained thing is `item.type`. For example, dnd uses that to distinguish weapons from backpacks. From what I see, PF2 has similar approach: 

```json
  "Item": {
    "types": [
      "weapon",
      "melee",
      "armor",
      "equipment",
      "consumable",
      "treasure",
      "lore",
      "martial",
      "spell",
      "spellcastingEntry",
      "feat",
      "action",
      "backpack"
    ]
  }
```

I will investigate.

**Comment by Forien** [comment] 2020-06-28 17:32
![image](https://user-images.githubusercontent.com/11304207/85954200-13577680-b976-11ea-9f78-f2dcaf598847.png)

I might not get the system, but it seems it's assigning items the same as it would the original ones?

**Comment by apoapostolov** [comment] 2020-06-28 17:36
Okay, just confirmed it retains the type. Tanglefoot Bag is considered weapon, so adding it to inventory will add its unidentified item as weapon, which is a bit of spoiler what the item is. I know that this is a fringe case but it would be better if it were overridden as treasure in some cases, in others retaining the type (for unidentified items) is better. Can a conversion to Treasure be optional?

**Comment by Forien** [comment] 2020-06-28 17:42
I decided to retain items' types, because if it looks like a sword, smells like a sword and works as a sword, it must be some type of sword. 

But there is also underlying issue that various item types in some systems might be internally incompatible and cause conflicts. You can basically freely edit the item beside it's type, so you can hide a magical fiery greatsword and set icon to show some Lute and name it "Bard's Bludgeon" ;) 

As for conversion between types, that is **very specific** thing that should be done on system-by-system basis, or even on type-per-type basis. Currently out of scope, but I plan on making basic integrations **and** to expose full API to allow systems/other modules to integrate properly.

**Comment by apoapostolov** [comment] 2020-06-28 17:43
The way I see it, a new Make Treasure button for Unidentified items would be enough to fix this.

**Closed** 2020-07-12 23:15 UTC
Labels: bug
