### ISSUE TITLE
Unidentified item still listed as identified

### ISSUE THREAD

**Issue by Pecomica** [Forien/foundryvtt-forien-unidentified-items#6] opened 2020-06-26 23:06 UTC
When mystifying an item it still have the tick in the identified button. If it is an unknown item it shouldn't.

**Comment by Forien** [comment] 2020-06-27 07:55
I believe you are mentioning something system specific. As I many times said, at the current state, this module does not retain any system-specific data.  
It retains only one thing: `type`. 

What you are talking about is probably in dnd5e, checkbox to check if item is identified or not. For the best of my knowledge that checkbox has no meaning and no mechanical value to the game system on Foundry.

But you can still freely edit the unidentified item to fit your needs.

Some _basic_ system integration will come in future.

**Comment by Forien** [comment] 2020-06-27 07:57
Duplicate of #5

**Closed** 2020-06-27 11:49 UTC
Labels: duplicate
